//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const MIGRATE_TO_WALLET_ADDRESS_V1_DISCRIMINATOR: u8 = 12;

/// Accounts.
#[derive(Debug)]
pub struct MigrateToWalletAddressV1 {
    /// the swig smart wallet to migrate
    pub swig: solana_pubkey::Pubkey,
    /// authority with manage authority permission or admin
    pub authority: solana_pubkey::Pubkey,
    /// the payer
    pub payer: solana_pubkey::Pubkey,
    /// the swig wallet address account to create
    pub swig_wallet_address: solana_pubkey::Pubkey,
    /// the system program
    pub system_program: solana_pubkey::Pubkey,
}

impl MigrateToWalletAddressV1 {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.swig, false));
        accounts.push(solana_instruction::AccountMeta::new(self.authority, true));
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new(
            self.swig_wallet_address,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = MigrateToWalletAddressV1InstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MigrateToWalletAddressV1InstructionData {
    discriminator: u8,
}

impl MigrateToWalletAddressV1InstructionData {
    pub fn new() -> Self {
        Self { discriminator: 12 }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for MigrateToWalletAddressV1InstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `MigrateToWalletAddressV1`.
///
/// ### Accounts:
///
///   0. `[writable]` swig
///   1. `[writable, signer]` authority
///   2. `[writable, signer]` payer
///   3. `[writable]` swig_wallet_address
///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct MigrateToWalletAddressV1Builder {
    swig: Option<solana_pubkey::Pubkey>,
    authority: Option<solana_pubkey::Pubkey>,
    payer: Option<solana_pubkey::Pubkey>,
    swig_wallet_address: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl MigrateToWalletAddressV1Builder {
    pub fn new() -> Self {
        Self::default()
    }
    /// the swig smart wallet to migrate
    #[inline(always)]
    pub fn swig(&mut self, swig: solana_pubkey::Pubkey) -> &mut Self {
        self.swig = Some(swig);
        self
    }
    /// authority with manage authority permission or admin
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// the payer
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// the swig wallet address account to create
    #[inline(always)]
    pub fn swig_wallet_address(&mut self, swig_wallet_address: solana_pubkey::Pubkey) -> &mut Self {
        self.swig_wallet_address = Some(swig_wallet_address);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// the system program
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = MigrateToWalletAddressV1 {
            swig: self.swig.expect("swig is not set"),
            authority: self.authority.expect("authority is not set"),
            payer: self.payer.expect("payer is not set"),
            swig_wallet_address: self
                .swig_wallet_address
                .expect("swig_wallet_address is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `migrate_to_wallet_address_v1` CPI accounts.
pub struct MigrateToWalletAddressV1CpiAccounts<'a, 'b> {
    /// the swig smart wallet to migrate
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// authority with manage authority permission or admin
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// the payer
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// the swig wallet address account to create
    pub swig_wallet_address: &'b solana_account_info::AccountInfo<'a>,
    /// the system program
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `migrate_to_wallet_address_v1` CPI instruction.
pub struct MigrateToWalletAddressV1Cpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// the swig smart wallet to migrate
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// authority with manage authority permission or admin
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// the payer
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// the swig wallet address account to create
    pub swig_wallet_address: &'b solana_account_info::AccountInfo<'a>,
    /// the system program
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> MigrateToWalletAddressV1Cpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: MigrateToWalletAddressV1CpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            swig: accounts.swig,
            authority: accounts.authority,
            payer: accounts.payer,
            swig_wallet_address: accounts.swig_wallet_address,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(5 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.swig.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.swig_wallet_address.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = MigrateToWalletAddressV1InstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.swig.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.swig_wallet_address.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `MigrateToWalletAddressV1` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` swig
///   1. `[writable, signer]` authority
///   2. `[writable, signer]` payer
///   3. `[writable]` swig_wallet_address
///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct MigrateToWalletAddressV1CpiBuilder<'a, 'b> {
    instruction: Box<MigrateToWalletAddressV1CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> MigrateToWalletAddressV1CpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(MigrateToWalletAddressV1CpiBuilderInstruction {
            __program: program,
            swig: None,
            authority: None,
            payer: None,
            swig_wallet_address: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// the swig smart wallet to migrate
    #[inline(always)]
    pub fn swig(&mut self, swig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.swig = Some(swig);
        self
    }
    /// authority with manage authority permission or admin
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// the payer
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// the swig wallet address account to create
    #[inline(always)]
    pub fn swig_wallet_address(
        &mut self,
        swig_wallet_address: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.swig_wallet_address = Some(swig_wallet_address);
        self
    }
    /// the system program
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = MigrateToWalletAddressV1Cpi {
            __program: self.instruction.__program,

            swig: self.instruction.swig.expect("swig is not set"),

            authority: self.instruction.authority.expect("authority is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            swig_wallet_address: self
                .instruction
                .swig_wallet_address
                .expect("swig_wallet_address is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct MigrateToWalletAddressV1CpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    swig: Option<&'b solana_account_info::AccountInfo<'a>>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    swig_wallet_address: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
