//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const SUB_ACCOUNT_SIGN_V1_DISCRIMINATOR: u8 = 9;

/// Accounts.
#[derive(Debug)]
pub struct SubAccountSignV1 {
    /// the swig smart wallet
    pub swig: solana_pubkey::Pubkey,
    /// the sub account
    pub sub_account: solana_pubkey::Pubkey,
    /// the system program
    pub system_program: solana_pubkey::Pubkey,
}

impl SubAccountSignV1 {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.swig, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.sub_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = SubAccountSignV1InstructionData::new().try_to_vec().unwrap();

        solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SubAccountSignV1InstructionData {
    discriminator: u8,
}

impl SubAccountSignV1InstructionData {
    pub fn new() -> Self {
        Self { discriminator: 9 }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for SubAccountSignV1InstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `SubAccountSignV1`.
///
/// ### Accounts:
///
///   0. `[]` swig
///   1. `[writable]` sub_account
///   2. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct SubAccountSignV1Builder {
    swig: Option<solana_pubkey::Pubkey>,
    sub_account: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SubAccountSignV1Builder {
    pub fn new() -> Self {
        Self::default()
    }
    /// the swig smart wallet
    #[inline(always)]
    pub fn swig(&mut self, swig: solana_pubkey::Pubkey) -> &mut Self {
        self.swig = Some(swig);
        self
    }
    /// the sub account
    #[inline(always)]
    pub fn sub_account(&mut self, sub_account: solana_pubkey::Pubkey) -> &mut Self {
        self.sub_account = Some(sub_account);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// the system program
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = SubAccountSignV1 {
            swig: self.swig.expect("swig is not set"),
            sub_account: self.sub_account.expect("sub_account is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `sub_account_sign_v1` CPI accounts.
pub struct SubAccountSignV1CpiAccounts<'a, 'b> {
    /// the swig smart wallet
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// the sub account
    pub sub_account: &'b solana_account_info::AccountInfo<'a>,
    /// the system program
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `sub_account_sign_v1` CPI instruction.
pub struct SubAccountSignV1Cpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// the swig smart wallet
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// the sub account
    pub sub_account: &'b solana_account_info::AccountInfo<'a>,
    /// the system program
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> SubAccountSignV1Cpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SubAccountSignV1CpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            swig: accounts.swig,
            sub_account: accounts.sub_account,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.swig.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.sub_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = SubAccountSignV1InstructionData::new().try_to_vec().unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.swig.clone());
        account_infos.push(self.sub_account.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SubAccountSignV1` via CPI.
///
/// ### Accounts:
///
///   0. `[]` swig
///   1. `[writable]` sub_account
///   2. `[]` system_program
#[derive(Clone, Debug)]
pub struct SubAccountSignV1CpiBuilder<'a, 'b> {
    instruction: Box<SubAccountSignV1CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SubAccountSignV1CpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SubAccountSignV1CpiBuilderInstruction {
            __program: program,
            swig: None,
            sub_account: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// the swig smart wallet
    #[inline(always)]
    pub fn swig(&mut self, swig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.swig = Some(swig);
        self
    }
    /// the sub account
    #[inline(always)]
    pub fn sub_account(
        &mut self,
        sub_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.sub_account = Some(sub_account);
        self
    }
    /// the system program
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = SubAccountSignV1Cpi {
            __program: self.instruction.__program,

            swig: self.instruction.swig.expect("swig is not set"),

            sub_account: self
                .instruction
                .sub_account
                .expect("sub_account is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SubAccountSignV1CpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    swig: Option<&'b solana_account_info::AccountInfo<'a>>,
    sub_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
