//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const TOGGLE_SUB_ACCOUNT_V1_DISCRIMINATOR: u8 = 10;

/// Accounts.
#[derive(Debug)]
pub struct ToggleSubAccountV1 {
    /// the swig smart wallet
    pub swig: solana_pubkey::Pubkey,
    /// the payer
    pub payer: solana_pubkey::Pubkey,
    /// the sub account to toggle enabled state
    pub sub_account: solana_pubkey::Pubkey,
}

impl ToggleSubAccountV1 {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.swig, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.payer, true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.sub_account,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = ToggleSubAccountV1InstructionData::new()
            .try_to_vec()
            .unwrap();

        solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ToggleSubAccountV1InstructionData {
    discriminator: u8,
}

impl ToggleSubAccountV1InstructionData {
    pub fn new() -> Self {
        Self { discriminator: 10 }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ToggleSubAccountV1InstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `ToggleSubAccountV1`.
///
/// ### Accounts:
///
///   0. `[writable]` swig
///   1. `[signer]` payer
///   2. `[writable]` sub_account
#[derive(Clone, Debug, Default)]
pub struct ToggleSubAccountV1Builder {
    swig: Option<solana_pubkey::Pubkey>,
    payer: Option<solana_pubkey::Pubkey>,
    sub_account: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ToggleSubAccountV1Builder {
    pub fn new() -> Self {
        Self::default()
    }
    /// the swig smart wallet
    #[inline(always)]
    pub fn swig(&mut self, swig: solana_pubkey::Pubkey) -> &mut Self {
        self.swig = Some(swig);
        self
    }
    /// the payer
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// the sub account to toggle enabled state
    #[inline(always)]
    pub fn sub_account(&mut self, sub_account: solana_pubkey::Pubkey) -> &mut Self {
        self.sub_account = Some(sub_account);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ToggleSubAccountV1 {
            swig: self.swig.expect("swig is not set"),
            payer: self.payer.expect("payer is not set"),
            sub_account: self.sub_account.expect("sub_account is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `toggle_sub_account_v1` CPI accounts.
pub struct ToggleSubAccountV1CpiAccounts<'a, 'b> {
    /// the swig smart wallet
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// the payer
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// the sub account to toggle enabled state
    pub sub_account: &'b solana_account_info::AccountInfo<'a>,
}

/// `toggle_sub_account_v1` CPI instruction.
pub struct ToggleSubAccountV1Cpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// the swig smart wallet
    pub swig: &'b solana_account_info::AccountInfo<'a>,
    /// the payer
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// the sub account to toggle enabled state
    pub sub_account: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> ToggleSubAccountV1Cpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ToggleSubAccountV1CpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            swig: accounts.swig,
            payer: accounts.payer,
            sub_account: accounts.sub_account,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.swig.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.payer.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.sub_account.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = ToggleSubAccountV1InstructionData::new()
            .try_to_vec()
            .unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SWIG_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.swig.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.sub_account.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ToggleSubAccountV1` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` swig
///   1. `[signer]` payer
///   2. `[writable]` sub_account
#[derive(Clone, Debug)]
pub struct ToggleSubAccountV1CpiBuilder<'a, 'b> {
    instruction: Box<ToggleSubAccountV1CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ToggleSubAccountV1CpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ToggleSubAccountV1CpiBuilderInstruction {
            __program: program,
            swig: None,
            payer: None,
            sub_account: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// the swig smart wallet
    #[inline(always)]
    pub fn swig(&mut self, swig: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.swig = Some(swig);
        self
    }
    /// the payer
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// the sub account to toggle enabled state
    #[inline(always)]
    pub fn sub_account(
        &mut self,
        sub_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.sub_account = Some(sub_account);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ToggleSubAccountV1Cpi {
            __program: self.instruction.__program,

            swig: self.instruction.swig.expect("swig is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            sub_account: self
                .instruction
                .sub_account
                .expect("sub_account is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ToggleSubAccountV1CpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    swig: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    sub_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
