[package]
name = "yellowstone-vixen-core"
description = "Core types for Vixen"
# authors = ["TODO"]
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"
readme = "./../../README.md"

[dependencies]
bs58.workspace = true
thiserror.workspace = true
yellowstone-grpc-proto = { workspace = true }
yellowstone-vixen-proto = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }

[features]
proto = ["dep:yellowstone-vixen-proto"]
